### PR TITLE
fix a small bug to allow .txt file to be loaded as lyric.

### PR DESCRIPTION
**Pull request by donin1129**
@reckel-jm we would like to use your software with easy installation. it would be really sweet if you could provide us a realease for this so we can install using exe file. many many thanks.

### CODE REVIEW

**Comment by reckel-jm** [comment]
Hello @donin1129,

Thank you very much for the bug report and the pull request! You are right that the code used in the `lyrics.pas` was not consistent and lead to a wrong result in some cases. Thanks for pointing that out. I just have removed the if-statement completely because the function `TSong.isCcliFile` already checks for the file format.

Now you should be able to import files with the ending .txt–and the format should be recognized correctly. If this is not the case, please feel free to provide an example song, so that I can check again with you.

I will merge your pull request and publish a bugfix release soon. When the merge is completed, Github will automatically generate an exe file which you can use in the meantime. I can also generate an other installer file for you if needed.

Please let me know if you need any further assistant or help with the software.

Thanks and have a nice weekend!

**Review by reckel-jm — APPROVED** [review]

**Comment by reckel-jm** [comment]
@donin1129 under the artefacts section of the link, you can find the executables for the last build: https://github.com/reckel-jm/cantara/actions/runs/10009073492

This is not an installer yet but should work fine. I will publish a release in the next days.

**Comment by donin1129** [comment]
thank you very much! keep up with the great work. good luck with everything.

**Comment by reckel-jm** [comment]
@donin1129 Thanks for your reply and your nice words! Please feel free to test the new version and tell me if there are still any problems or wishes for improvement.

God bless you and your church/fellowship!

**Comment by reckel-jm** [comment]
@donin1129 here you find a beta release with an easy installer: https://github.com/reckel-jm/cantara/releases/tag/v2.6.1-beta

Note that on Windows, you might get warnings that the executable is unverified/unsigned. That is because I haven't released the new version into the winger repository yet. You can bypass the warnings and still install Cantara.

**Comment by reckel-jm** [comment]
Hey @donin1129, could you already test the beta release and confirm that it is working as you would like to?

**Comment by donin1129** [comment]
Hi @reckel-jm , Than you very very much for your release. Everything is working as smooth as possible. Many many appreciations!

**Comment by reckel-jm** [comment]
@donin1129 Thank you for the response! I will publish a new main release in the next couple of weeks as well.

If you like Cantara, I would be happy if you would consider giving a *star* to the Github project and recommend it to friends. In that way, hopefully more people will use it and provide contributions.

Thank you and God bless!

**Pull request merged**
